services:
  backend:
    build:
      context: .
      dockerfile: deploy/backend/Dockerfile
    volumes:
      - ./config.yml:/config.yml
    environment:
      - CONFIG_PATH=/config.yml
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: deploy/frontend/Dockerfile
    volumes:
      - ./config.yml:/config.yml
    restart: always
    ports:
      - 3000:3000
  agent:
    build:
      context: .
      dockerfile: deploy/agent/Dockerfile
    volumes:
      - ./config.yml:/config.yml
      - ./mounts.yml:/mounts.yml
      - agent-data:/data
    restart: always
  db:
    image: postgres:17
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypgpass
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  postgres-data:
  agent-data:
